FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY package.json ./
RUN npm install
COPY prisma ./prisma
COPY . .
RUN npx prisma generate
CMD npx prisma db push --accept-data-loss && \
    echo "Ensuring columns exist..." && \
    node prisma/ensure-columns.js && \
    npx tsx prisma/seed.ts
